test_name: Test_create_collection and documents operations

stages:
  - name: create collection
    request:
      url: http://127.0.0.1:8001/indexes/collections
      method: POST
      headers:
        Content-Type: application/json
      json:
        name: "test"
        fields:
          - name: "id"
            type: "int"
          - name: "name"
            type: "string"
          - name: "content"
            type: "string"
    response:
      status_code: 201
      save:
          json:
              collection_name: name

  - name: get list of collections
    request:
      url: "http://127.0.0.1:8001/indexes/{collection_name}/documents?offset=0&limit=15"
      method: GET
      headers:
        Content-Type: application/json
      params:
        offset: 0
        limit: 15
    response:
      status_code: 200

  -   name: get collection
      request:
          url: "http://127.0.0.1:8001/indexes/collections/{collection_name}"
          method: GET
          headers:
              Content-Type: application/json
      response:
          status_code: 200

  -   name: delete collection
      request:
          url: "http://127.0.0.1:8001/indexes/collections/{collection_name}"
          method: DELETE
          headers:
              Content-Type: application/json
      response:
          status_code: 200
